# Generated by Django 5.0.6 on 2024-08-03 02:14

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipofutbol')),
                ('seleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.selecciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_subida'],
                'permissions': [('add_noticia', 'Puede añadir noticias'), ('change_noticia', 'Puede cambiar noticias'), ('delete_noticia', 'Puede borrar noticias')],
                'indexes': [models.Index(fields=['-fecha_subida'], name='noticias_no_fecha_s_41ee9d_idx')],
            },
        ),
    ]
