# Generated by Django 5.0.6 on 2024-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.CharField(max_length=550),
        ),
    ]
