# Generated by Django 5.0.6 on 2024-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
