# Generated by Django 5.0.6 on 2024-06-29 03:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
