# Generated by Django 5.0.6 on 2024-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='noticias_publicadas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
