# Generated by Django 5.0.6 on 2024-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_noticias_publicadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='noticias_publicadas',
            field=models.IntegerField(default=0),
        ),
    ]
