# Generated by Django 5.0.6 on 2024-06-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_noticias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipofutbol',
            name='logo',
        ),
    ]
