# Generated by Django 5.0.6 on 2024-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Equipo Futbol',
                'verbose_name_plural': 'Equipos de Futbol',
            },
        ),
        migrations.CreateModel(
            name='Selecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Seleccion',
                'verbose_name_plural': 'Selecciones',
            },
        ),
    ]
