# Generated by Django 5.0.6 on 2024-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipofutbol',
            name='url',
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='fecha_fundacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='equipofutbol',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
