# Generated by Django 5.0.6 on 2024-10-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipofutbol_url_equipofutbol_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipofutbol',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='equipofutbol',
            name='fecha_fundacion',
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='apodo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='cantidad_socios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='director_tecnico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='entrenador_mas_ganador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='estadio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='goleador_historico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='jugador_mas_partidos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='jugador_mas_titulos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='jugadores_historicos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='plantel_actual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='presidente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='vicepresidente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipofutbol',
            name='historia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipofutbol',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='equipofutbol',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
