# Generated by Django 5.0.6 on 2024-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipofutbol_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipofutbol',
            name='ciudad',
            field=models.TextField(blank=True),
        ),
    ]
