# Generated by Django 5.0.6 on 2024-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipofutbol_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('posicion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipofutbol',
            name='jugadores_historicos',
        ),
        migrations.AddField(
            model_name='equipofutbol',
            name='jugadores_historicos',
            field=models.ManyToManyField(blank=True, related_name='equipos_historicos', to='equipos.jugador'),
        ),
    ]
